### ISSUE TITLE
Modify settings via console command

### ISSUE THREAD

**Issue by Quentin-ctrL** [shudnal/GammaOfNightLights#1]
Hi,

How can I modify settings via console command ?

Regards

**Comment by shudnal** [comment]
You can't control setting via console as it didn't design to work like this at all.
You can control settings via config file editing at BepInEx/config/ folder. This mod's config file is named shudnal.GammaOfNightLights.cfg
But best option is to use Configuration Manager mod to do it ingame with immediate effect.

There is updated version https://valheim.thunderstore.io/package/Azumatt/Official_BepInEx_ConfigurationManager/ 

My own choice is [ConfigurationManager.zip](https://github.com/shudnal/GammaOfNightLights/files/12643701/ConfigurationManager.zip)

 it's fixed version of https://www.nexusmods.com/valheim/mods/740.

EDIT: Didn't noticed the author of latter mod did a rework. There is another option https://www.nexusmods.com/site/mods/529

**Comment by shudnal** [comment]
Added links to configuration managers to description.
