### ISSUE TITLE
Luminance in dark env

### ISSUE THREAD

**Issue by FPSTordah** [shudnal/GammaOfNightLights#3]
Hi there,

My server folks have been fighting with the gamma setting, specifically the Luminance in dark env's. I am here at one of the computers and the setting changes nothing when inside their house, in fact last night one was complaining they couldn't see in the cave and their setting was at 60, but it was so very dark.

I have tried with the set luminance outdoors to false and true and still no change. Is there something we are doing wrong?

**Comment by shudnal** [comment]
Hi,

I think I should have left an explanation on the mod page. This setting may be confusing.

There is an object called EnvMan. It controls current ingame environment of your character. It contains distinct settings for night and day. And it have the setting called m_alwaysDark that takes values true/false.
That setting set to true in environments like Rain, SwampRain, Thunderstorm, Ashrain and so on. Basiaclly it means the generated lights should be dimmed while this environment is active. That setting is also on in all dungeon environments.

So my setting "Luminance in dark environments" means that the lights of the environment will be corrected by set factor when the active environment have m_alwaysDark on. It doesn't cross with "Luminance at night" but only control daylight gamma in this environments.

Some examples
Daytime. Outdoors. Weather is Clear. No luminance setting can be applied.
Daytime. Outdoors. Weather is Rain. "Luminance in dark environments" is applied.
Daytime. Indoors. Weather is Crypt. If "Set luminance only outdoors" is on - nothing applied. If "Set luminance only outdoors" is off - "Luminance in dark environments" is applied.
Nighttime. Outdoors. Weather is Clear. "Luminance at night" applied.
Nighttime. Outdoors. Weather is SwampRain. "Luminance at night" applied.
Nighttime. Outdoors. Weather is SunkenCrypt. If "Set luminance only outdoors" is on - nothing applied. If "Set luminance only outdoors" is off - "Luminance in dark environments" is applied.

While I wrote this I have come to mind that we just need distinct setting for indoors.

Also indoors doesn't mean "in the house" or "under roof". It's only count instanced locations like caves, crypts and so on.

**Comment by shudnal** [comment]
@FPSTordah Pls check new 1.0.1 version. Now settings are more straightforward without confusing.

**Comment by shudnal** [comment]
I can not do more specific settings than now.
